---
title: "Redes Neurais e Regressão Polinomial"
author:
- Luiz Fernando Palin Droubi^[UFSC, luiz.droubi@planejamento.gov.br]
- Carlos Augusto Zilli^[UFSC, carloszilli@hotmail.com]
- Norberto Hochheim^[UFSC, hochheim@gmail.com]
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
output:
  pdf_document:
    includes:
      in_header: preamble.tex
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
    toc: no
  word_document: default
  html_document:
    fig_caption: yes
    keep_md: yes
classoption: a4paper, 12pt
documentclass: article
geometry: left=3.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm
link-citations: yes
linkcolor: red
urlcolor: magenta
citecolor: green
csl: ABNT_UFPR_2011-Mendeley.csl
subtitle: Um estudo de caso
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, 
                      warning = FALSE)
library(appraiseR)
library(neuralnet)
library(polyreg)
```



```{r}
## Creating index variable 

# Read the Data
data = centro_2015@data[complete.cases(centro_2015@data),]
data$padrao <- as.numeric(data$padrao)

# Random sampling
samplesize = 0.60*nrow(data)
set.seed(80)
index = sample( seq_len(nrow(data)), size = samplesize)

# Create training and test set
datatrain = data[ index, ]
datatest = data[ -index, ]
```

```{r}
## Scale data for neural network
max = apply(data, 2, max)
min = apply(data, 2, min)
scaled = as.data.frame(scale(data, center = min, scale = max - min))
```

```{r}
## Fit neural network 

# creating training and test set
trainNN = scaled[index , ]
testNN = scaled[-index , ]

# fit neural network
set.seed(2)
NN = neuralnet(valor ~ area_total + quartos + suites + garagens + 
                 dist_b_mar + padrao, 
               data = trainNN, hidden = 1, linear.output = T )

# plot neural network
plot(NN)

```

## Estimativas

```{r}
## Prediction using neural network

predict_testNN = compute(NN, testNN[,2:7])
predict_testNN = (predict_testNN$net.result * 
                    (max(data$valor) - min(data$valor))) + 
                  min(data$valor)

plot(datatest$valor, predict_testNN, col='blue', pch=16, 
     ylab = "predicted rating NN", xlab = "Valor")

abline(0,1)

# Calculate Root Mean Square Error (RMSE)
RMSE.NN = (sum((datatest$valor - 
                  predict_testNN)^2) / nrow(datatest)) ^ 0.5
```

## Validação Cruzada

```{r, cache = TRUE}
## Cross validation of neural network model

# Load libraries
library(boot)
library(plyr)

# Initialize variables
set.seed(50)
k = 100
RMSE.NN = NULL
n <- nrow(data)

List = list()

# Fit neural network model within nested for loop
for(j in seq(0.2, 0.9, 0.02)){
    for (i in 1:k) {
        index = sample(1:n,j*n )

        trainNN = scaled[index,]
        testNN = scaled[-index,]
        datatest = data[-index,]

        NN = neuralnet(valor ~ area_total + quartos + suites + 
                         garagens + dist_b_mar + padrao,
                       trainNN, hidden = 1, linear.output= T)
        predict_testNN = compute(NN,testNN[,c(2:7)])
        predict_testNN = (predict_testNN$net.result*
                            (max(data$valor) - min(data$valor))) +
                          min(data$valor)

        RMSE.NN[i]<- sqrt(sum((datatest$valor - predict_testNN)^2)/
                            nrow(datatest))
    }
    List[[j*n]] = RMSE.NN
}

Matrix.RMSE = do.call(cbind, List)

## Prepare boxplot
boxplot(Matrix.RMSE[,36], 
        ylab = "RMSE", 
        main = "RMSE BoxPlot (length of traning set = 45)")

```

```{r}
## Variation of median RMSE 
library(matrixStats)

med = colMedians(Matrix.RMSE)

X = seq(0.2, 0.9, 0.02)*n

plot (med~X, type = "l", 
      xlab = "length of training set", 
      ylab = "median RMSE", 
      main = "Variation of RMSE with length of training set")
```

# REGRESSÃO POLINOMIAL

```{r, results ='hide'}
data <- cbind(data[, -1], data[,1])

# Initialize variables
set.seed(50)
k = 100
RMSE.PR = NULL
n <- nrow(data)

List = list()

# Fit PR model within nested for loop
for(j in seq(0.2, 0.9, 0.02)){
  for (i in 1:k) {
    index = sample(1:n,j*n )
    trainPR = data[index,]
    testPR = data[-index,]
    polyFit.out <- polyFit(trainPR, deg = 2, maxInteractDeg = 2, 
                           use = "lm", pcaMethod = "prcomp")
    predict_testPR = predict(polyFit.out, testPR[,c(1:6)])
    RMSE.PR[i]<- sqrt(sum((testPR$valor - predict_testPR)^2)/
                        nrow(trainPR))
    }
  List[[j*n]] = RMSE.PR
}


Matrix.RMSE = do.call(cbind, List)

## Prepare boxplot
boxplot(Matrix.RMSE[,36], 
        ylab = "RMSE", 
        main = "RMSE BoxPlot (length of traning set = 45)")
```

```{r}
## Variation of median RMSE 
med = colMedians(Matrix.RMSE)

X = seq(0.2, 0.9, 0.02)*n

plot (med~X, type = "l", 
      xlab = "length of training set", 
      ylab = "median RMSE", 
      main = "Variation of RMSE with length of training set")
```

# CONCLUSÕES E RECOMENDAÇÕES

# REFERÊNCIAS
